import './vendors';

import './modules/_default';
import './modules/_pageLoadMore';
import './modules/_form';
import './modules/_modals';
import './modules/_submenu';
import './modules/_menu';
import './modules/_button';
import './modules/_accordion';
import './modules/_tables';
import './modules/_tabs';
import './modules/_select';
import './modules/_toswiper';
import './modules/_moving.js';
import './modules/_loadsvg';
import './modules/_map';
import './modules/_thousandSeparator';
import './modules/_sizes';